spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      master:  #数据源1
        url: jdbc:mysql://192.168.56.109:3306/houyi?useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: macro
        password: macro@123
      slave: #数据源2
        url: jdbc:mysql://192.168.1.63:3306/houyi?useSSL=false&useUnicode=true&characterEncoding=utf-8
        username: houyi
        password: houyi
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /jbt
  port: 8080