spring:
  datasource:
    url: jdbc:mysql://192.168.56.109/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: macro
    password: macro@123
    driver-class-name: com.mysql.jdbc.Driver

server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /
  port: 8080